spring.application.name=gestion-restaurants
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_restaurants?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka (API Gateway sur 8085 + serveur Eureka sur 8761)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# RabbitMQ (producer statut restaurant → gestion-livraison)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
