spring.application.name=ApiGatway
server.port=8085

# Eureka
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Gateway CORS support
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].exposedHeaders=Authorization
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600
spring.cloud.gateway.default-filters[0]=SetResponseHeader=Access-Control-Allow-Origin, http://localhost:4200
spring.cloud.gateway.default-filters[1]=SetResponseHeader=Access-Control-Allow-Credentials, true
spring.cloud.gateway.default-filters[2]=SetResponseHeader=Access-Control-Expose-Headers, Authorization
spring.cloud.gateway.default-filters[3]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Headers Access-Control-Allow-Methods Access-Control-Expose-Headers RETAIN_FIRST
spring.cloud.gateway.httpserver.wiretap=true